In [1]:
#statsmodel is a Python lib for fitting many kinds of statistical models, performing statistical tests, and
#data explorations and visualization.
#Statsmodel contains more "classical" frequentist statistical methods, while Bayesian method and machine learning
#models are found in other libraries.
#Some Kind of models found in statsmodels include:
#* Linear models, generalized linear model, and robust linear model
#* Linear mixed effects models
#* Analysis of Variance methods
#* Time series process and state space models
#* Generalized metjod of moments

# Estimating Linear Models

In [2]:
#There are several kinds of linear regression models in statsmodels, from the more basic
#to more complex (e.g iteratively reweighted least squares)
#Linear models in statsmodels have two diffrent main interfaces: array-based and formula-based.
#This are accessed through there API module imports:

In [3]:
import statsmodels.api as sm
import statsmodels.formula.api as smf

In [4]:
#To show how to use these, we generate a linear model from some random data:

In [5]:
def dnorm(mean, variance, size=1):
    if isinstance(size, int):
        size = size,
        return mean + np.sqrt(variance) * np.random.randn(*size)

In [7]:
import numpy as np

In [9]:
# For repoductibility
np.random.seed(12345)
N = 100
X = np.c_[dnorm(0, 0.4, size=N),
          dnorm(0, 0.6, size=N),
          dnorm(0, 0.2, size=N),
         ]
eps = dnorm(0 ,0.1, size=N)
beta = [0.1, 0.3, 0.5]
y = np.dot(X, beta)+eps

In [10]:
y

array([ 0.42786349, -0.67348041, -0.09087764, -0.48949442, -0.12894109,
       -0.04501494,  0.08757735, -0.50456809, -0.54582359,  0.26527124,
        0.59784431,  0.45268655,  0.08698737,  0.05540612, -0.09117045,
        0.14472907, -0.15127161, -0.05633559,  1.2167688 , -0.02230032,
       -0.69063922,  0.08524475,  0.73444882, -0.35271834, -0.25469893,
        0.30780133,  0.70383282, -0.5331801 , -0.22072084, -0.09677542,
       -0.49691476, -1.33344177, -0.37685375,  1.25999316, -0.29484543,
       -0.61445479,  0.18725508, -0.40779804,  0.05730302,  0.4745453 ,
       -0.43516233,  0.03148314, -0.05635841,  0.12133475,  0.22345618,
        0.05955794,  0.25805322, -0.2750181 ,  0.30513496, -0.20032791,
        0.08627269, -0.42451706,  0.23481135, -0.32057314,  0.67561398,
       -0.38726135, -0.37863875, -0.16376385, -0.17011089,  0.39236031,
       -0.13687819,  0.18865275, -0.13990581,  0.61372834, -0.40825235,
        0.46866481, -0.59632133, -0.07708193,  0.70818684,  0.14

In [11]:
X[:5]

array([[-0.12946849, -1.21275292,  0.50422488],
       [ 0.30291036, -0.43574176, -0.25417986],
       [-0.32852189, -0.02530153,  0.13835097],
       [-0.35147471, -0.71960511, -0.25821463],
       [ 1.2432688 , -0.37379916, -0.52262905]])

In [12]:
y[:5]

array([ 0.42786349, -0.67348041, -0.09087764, -0.48949442, -0.12894109])

In [13]:
X_model = sm.add_constant(X)
X_model[:5]

array([[ 1.        , -0.12946849, -1.21275292,  0.50422488],
       [ 1.        ,  0.30291036, -0.43574176, -0.25417986],
       [ 1.        , -0.32852189, -0.02530153,  0.13835097],
       [ 1.        , -0.35147471, -0.71960511, -0.25821463],
       [ 1.        ,  1.2432688 , -0.37379916, -0.52262905]])

In [14]:
#The sm.OLS class can fit an ordinary least squares linear regession:

In [15]:
model = sm.OLS(y, X)
results = model.fit()
results.params

array([0.17826108, 0.22303962, 0.50095093])

In [16]:
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:                      y   R-squared (uncentered):                   0.430
Model:                            OLS   Adj. R-squared (uncentered):              0.413
Method:                 Least Squares   F-statistic:                              24.42
Date:                Sat, 22 Aug 2020   Prob (F-statistic):                    7.44e-12
Time:                        20:09:09   Log-Likelihood:                         -34.305
No. Observations:                 100   AIC:                                      74.61
Df Residuals:                      97   BIC:                                      82.42
Df Model:                           3                                                  
Covariance Type:            nonrobust                                                  
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1             0.1783      0.053      3.364      0.001       0.073       0.283
x2             0.2230      0.046      4.818      0.000       0.131       0.315
x3             0.5010      0.080      6.237      0.000       0.342       0.660
==============================================================================
Omnibus:                        4.662   Durbin-Watson:                   2.201
Prob(Omnibus):                  0.097   Jarque-Bera (JB):                4.098
Skew:                           0.481   Prob(JB):                        0.129
Kurtosis:                       3.243   Cond. No.                         1.74
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [18]:
import pandas as pd

In [19]:
data = pd.DataFrame(X, columns=['col0', 'col1', 'col2'])
data['y'] = y
data[:5]

col0      col1      col2         y
0 -0.129468 -1.212753  0.504225  0.427863
1  0.302910 -0.435742 -0.254180 -0.673480
2 -0.328522 -0.025302  0.138351 -0.090878
3 -0.351475 -0.719605 -0.258215 -0.489494
4  1.243269 -0.373799 -0.522629 -0.128941

In [20]:
results = smf.ols('y ~ col0 + col1 + col2', data=data).fit()
results.params

Intercept    0.033559
col0         0.176149
col1         0.224826
col2         0.514808
dtype: float64

In [21]:
results.tvalues

Intercept    0.952188
col0         3.319754
col1         4.850730
col2         6.303971
dtype: float64

In [23]:
results.predict(data[:5])

0   -0.002327
1   -0.141904
2    0.041226
3   -0.323070
4   -0.100535
dtype: float64

# Estimating Time Series Processes

In [28]:
#Another class of models in statsmodels are for time series analysis. Among these areautoregressive processes, 
#kalman filtering and other state space models, and multivariate autoregressive models.
#Let's simulate some time series data with an autoregressive structure and moise:
init_x = 4
import random
values = [init_x, init_x]
N = 1000
b0 = 0.8
b1 = -0.4
noise = dnorm(0, 0.1, N)
for i in range(N):
    new_x = values[-1] * b0 + values[-2] * b1 + noise[i]
    values.append(new_x)


In [29]:
MAXLAGS = 5

In [30]:
model = sm.tsa.AR(values)
results = model.fit(MAXLAGS)
results.params

array([ 0.00791554,  0.71074082, -0.31689896, -0.06724519,  0.0041215 ,
       -0.00079061])